import { ConnectorDefinition } from '../types';

export const cloudServices: ConnectorDefinition[] = [
  {
    id: 'salesforce',
    name: 'Salesforce',
    category: 'cloud-service',
    icon: 'cloud',
    description: 'Connect to Salesforce CRM data for sales and customer analytics.',
    authMethods: ['oauth2', 'username-password'],
    fields: [
      { id: 'instanceUrl', label: 'Instance URL', type: 'text', placeholder: 'https://yourorg.salesforce.com', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'securityToken', label: 'Security Token', type: 'password', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'salesforce-data-cloud',
    name: 'Salesforce Data Cloud',
    category: 'cloud-service',
    icon: 'cloud',
    description: 'Access unified customer data from Salesforce Data Cloud.',
    authMethods: ['oauth2'],
    fields: [
      { id: 'instanceUrl', label: 'Instance URL', type: 'text', required: true },
      { id: 'clientId', label: 'Client ID', type: 'text', required: true },
      { id: 'clientSecret', label: 'Client Secret', type: 'password', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'salesforce-datorama',
    name: 'Salesforce Datorama',
    category: 'cloud-service',
    icon: 'cloud',
    description: 'Marketing intelligence platform for cross-channel analytics.',
    authMethods: ['api-key'],
    fields: [
      { id: 'apiEndpoint', label: 'API Endpoint', type: 'text', required: true },
      { id: 'apiKey', label: 'API Key', type: 'password', required: true },
      { id: 'workspace', label: 'Workspace', type: 'text', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'salesforce-marketing-cloud',
    name: 'Salesforce Marketing Cloud',
    category: 'cloud-service',
    icon: 'cloud',
    description: 'Digital marketing platform for email, mobile, and social campaigns.',
    authMethods: ['oauth2'],
    fields: [
      { id: 'subdomain', label: 'Subdomain', type: 'text', placeholder: 'mc-xxx', required: true },
      { id: 'clientId', label: 'Client ID', type: 'text', required: true },
      { id: 'clientSecret', label: 'Client Secret', type: 'password', required: true },
      { id: 'accountId', label: 'Account ID', type: 'text', required: false },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'oracle-netsuite',
    name: 'Oracle Netsuite',
    category: 'cloud-service',
    icon: 'cloud',
    description: 'Cloud-based ERP and business management suite.',
    authMethods: ['oauth2', 'api-key'],
    fields: [
      { id: 'accountId', label: 'Account ID', type: 'text', required: true },
      { id: 'consumerKey', label: 'Consumer Key', type: 'password', required: true },
      { id: 'consumerSecret', label: 'Consumer Secret', type: 'password', required: true },
      { id: 'tokenId', label: 'Token ID', type: 'password', required: true },
      { id: 'tokenSecret', label: 'Token Secret', type: 'password', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'splunk',
    name: 'Splunk',
    category: 'cloud-service',
    icon: 'search',
    description: 'Platform for searching, monitoring, and analyzing machine data.',
    authMethods: ['username-password', 'api-key'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'splunk.example.com', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '8089', required: true, defaultValue: 8089 },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'ssl', label: 'Use SSL', type: 'checkbox', required: false, defaultValue: true },
    ],
    defaultPort: 8089,
    supportsSchemaDiscovery: false,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'denodo',
    name: 'Denodo',
    category: 'cloud-service',
    icon: 'layers',
    description: 'Data virtualization platform for real-time data integration.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '9999', required: true, defaultValue: 9999 },
      { id: 'database', label: 'Virtual Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 9999,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'google-looker',
    name: 'Google Looker',
    category: 'cloud-service',
    icon: 'eye',
    description: 'Business intelligence and data analytics platform by Google.',
    authMethods: ['api-key', 'oauth2'],
    fields: [
      { id: 'instanceUrl', label: 'Looker Instance URL', type: 'text', placeholder: 'https://yourcompany.looker.com', required: true },
      { id: 'clientId', label: 'Client ID', type: 'text', required: true },
      { id: 'clientSecret', label: 'Client Secret', type: 'password', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'cloud-service',
    icon: 'users',
    description: 'CRM platform for marketing, sales, and customer service data.',
    authMethods: ['api-key', 'oauth2'],
    fields: [
      { id: 'apiKey', label: 'API Key', type: 'password', required: true },
      { id: 'objectType', label: 'Object Type', type: 'select', required: false, options: [{ label: 'Contacts', value: 'contacts' }, { label: 'Companies', value: 'companies' }, { label: 'Deals', value: 'deals' }, { label: 'Tickets', value: 'tickets' }] },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'google-analytics',
    name: 'Google Analytics',
    category: 'cloud-service',
    icon: 'bar-chart',
    description: 'Web analytics service for tracking website traffic and user behavior.',
    authMethods: ['oauth2', 'service-account'],
    fields: [
      { id: 'propertyId', label: 'Property ID', type: 'text', placeholder: 'GA4 Property ID', required: true },
      { id: 'serviceAccountKey', label: 'Service Account Key (JSON)', type: 'textarea', required: true },
      { id: 'startDate', label: 'Start Date', type: 'text', placeholder: 'YYYY-MM-DD', required: false },
      { id: 'endDate', label: 'End Date', type: 'text', placeholder: 'YYYY-MM-DD', required: false },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'adobe-analytics',
    name: 'Adobe Analytics',
    category: 'cloud-service',
    icon: 'bar-chart',
    description: 'Enterprise analytics platform for digital marketing insights.',
    authMethods: ['oauth2', 'api-key'],
    fields: [
      { id: 'companyId', label: 'Company ID', type: 'text', required: true },
      { id: 'clientId', label: 'Client ID', type: 'text', required: true },
      { id: 'clientSecret', label: 'Client Secret', type: 'password', required: true },
      { id: 'reportSuiteId', label: 'Report Suite ID', type: 'text', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'marketo',
    name: 'Marketo',
    category: 'cloud-service',
    icon: 'mail',
    description: 'Marketing automation platform for lead management and campaigns.',
    authMethods: ['api-key'],
    fields: [
      { id: 'endpoint', label: 'REST API Endpoint', type: 'text', placeholder: 'https://xxx-xxx-xxx.mktorest.com', required: true },
      { id: 'clientId', label: 'Client ID', type: 'text', required: true },
      { id: 'clientSecret', label: 'Client Secret', type: 'password', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'servicenow',
    name: 'ServiceNow',
    category: 'cloud-service',
    icon: 'settings',
    description: 'IT service management platform for enterprise workflows.',
    authMethods: ['username-password', 'oauth2'],
    fields: [
      { id: 'instanceUrl', label: 'Instance URL', type: 'text', placeholder: 'https://yourinstance.service-now.com', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'table', label: 'Table Name', type: 'text', required: false },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'workday',
    name: 'Workday',
    category: 'cloud-service',
    icon: 'briefcase',
    description: 'Cloud-based HR and finance management platform.',
    authMethods: ['username-password', 'oauth2'],
    fields: [
      { id: 'tenant', label: 'Tenant Name', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'reportUrl', label: 'Report URL', type: 'text', required: false },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'jira',
    name: 'Jira',
    category: 'cloud-service',
    icon: 'check-square',
    description: 'Project management and issue tracking platform by Atlassian.',
    authMethods: ['api-key', 'oauth2'],
    fields: [
      { id: 'instanceUrl', label: 'Jira URL', type: 'text', placeholder: 'https://yourorg.atlassian.net', required: true },
      { id: 'email', label: 'Email', type: 'text', required: true },
      { id: 'apiToken', label: 'API Token', type: 'password', required: true },
      { id: 'project', label: 'Project Key', type: 'text', required: false },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    category: 'cloud-service',
    icon: 'headphones',
    description: 'Customer service and support ticketing platform.',
    authMethods: ['api-key', 'oauth2'],
    fields: [
      { id: 'subdomain', label: 'Subdomain', type: 'text', placeholder: 'yourcompany', required: true },
      { id: 'email', label: 'Email', type: 'text', required: true },
      { id: 'apiToken', label: 'API Token', type: 'password', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'cloud-service',
    icon: 'credit-card',
    description: 'Payment processing platform for online businesses.',
    authMethods: ['api-key'],
    fields: [
      { id: 'apiKey', label: 'Secret Key', type: 'password', required: true },
      { id: 'objectType', label: 'Object Type', type: 'select', required: false, options: [{ label: 'Charges', value: 'charges' }, { label: 'Customers', value: 'customers' }, { label: 'Invoices', value: 'invoices' }, { label: 'Subscriptions', value: 'subscriptions' }, { label: 'Payments', value: 'payments' }] },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'shopify',
    name: 'Shopify',
    category: 'cloud-service',
    icon: 'shopping-cart',
    description: 'E-commerce platform for online store analytics and data.',
    authMethods: ['api-key', 'oauth2'],
    fields: [
      { id: 'shopDomain', label: 'Shop Domain', type: 'text', placeholder: 'yourstore.myshopify.com', required: true },
      { id: 'accessToken', label: 'Access Token', type: 'password', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
];
