import { ConnectorDefinition } from '../types';

export const cloudWarehouses: ConnectorDefinition[] = [
  {
    id: 'amazon-athena',
    name: 'Amazon Athena',
    category: 'cloud-warehouse',
    icon: 'cloud',
    description: 'Query data in Amazon S3 using standard SQL with serverless infrastructure.',
    authMethods: ['iam-role', 'api-key'],
    fields: [
      { id: 'region', label: 'AWS Region', type: 'text', placeholder: 'us-east-1', required: true },
      { id: 'database', label: 'Database', type: 'text', placeholder: 'default', required: true },
      { id: 's3OutputLocation', label: 'S3 Output Location', type: 'text', placeholder: 's3://bucket/path/', required: true },
      { id: 'accessKeyId', label: 'Access Key ID', type: 'password', required: true },
      { id: 'secretAccessKey', label: 'Secret Access Key', type: 'password', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'amazon-aurora',
    name: 'Amazon Aurora',
    category: 'cloud-warehouse',
    icon: 'database',
    description: 'MySQL and PostgreSQL-compatible relational database built for the cloud.',
    authMethods: ['username-password', 'iam-role'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'cluster.region.rds.amazonaws.com', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '3306', required: true, defaultValue: 3306 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'ssl', label: 'Require SSL', type: 'checkbox', required: false, defaultValue: true },
    ],
    defaultPort: 3306,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'amazon-emr-hadoop-hive',
    name: 'Amazon EMR Hadoop Hive',
    category: 'cloud-warehouse',
    icon: 'server',
    description: 'Run Apache Hive queries on Amazon EMR clusters.',
    authMethods: ['username-password', 'iam-role'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'emr-master-node', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '10000', required: true, defaultValue: 10000 },
      { id: 'database', label: 'Database', type: 'text', placeholder: 'default', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: false },
      { id: 'transportMode', label: 'Transport Mode', type: 'select', required: true, defaultValue: 'binary', options: [{ label: 'Binary', value: 'binary' }, { label: 'HTTP', value: 'http' }] },
    ],
    defaultPort: 10000,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'amazon-redshift',
    name: 'Amazon Redshift',
    category: 'cloud-warehouse',
    icon: 'database',
    description: 'Fast, fully managed cloud data warehouse for analytics workloads.',
    authMethods: ['username-password', 'iam-role'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'cluster.region.redshift.amazonaws.com', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '5439', required: true, defaultValue: 5439 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'ssl', label: 'Require SSL', type: 'checkbox', required: false, defaultValue: true },
    ],
    defaultPort: 5439,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'alibaba-analyticsdb',
    name: 'Alibaba AnalyticsDB',
    category: 'cloud-warehouse',
    icon: 'database',
    description: 'Real-time data warehousing service on Alibaba Cloud.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '3306', required: true, defaultValue: 3306 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 3306,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'alibaba-data-lake-analytics',
    name: 'Alibaba Data Lake Analytics',
    category: 'cloud-warehouse',
    icon: 'cloud',
    description: 'Serverless interactive query service for data lakes on Alibaba Cloud.',
    authMethods: ['api-key'],
    fields: [
      { id: 'endpoint', label: 'Endpoint', type: 'text', required: true },
      { id: 'accessKeyId', label: 'Access Key ID', type: 'password', required: true },
      { id: 'accessKeySecret', label: 'Access Key Secret', type: 'password', required: true },
      { id: 'database', label: 'Database', type: 'text', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'alibaba-maxcompute',
    name: 'Alibaba MaxCompute',
    category: 'cloud-warehouse',
    icon: 'cloud',
    description: 'Fully managed big data processing platform on Alibaba Cloud.',
    authMethods: ['api-key'],
    fields: [
      { id: 'endpoint', label: 'Endpoint', type: 'text', required: true },
      { id: 'project', label: 'Project', type: 'text', required: true },
      { id: 'accessKeyId', label: 'Access Key ID', type: 'password', required: true },
      { id: 'accessKeySecret', label: 'Access Key Secret', type: 'password', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'databricks',
    name: 'Databricks',
    category: 'cloud-warehouse',
    icon: 'zap',
    description: 'Unified analytics platform for data engineering and data science.',
    authMethods: ['api-key', 'oauth2'],
    fields: [
      { id: 'host', label: 'Server Hostname', type: 'text', placeholder: 'adb-xxx.azuredatabricks.net', required: true },
      { id: 'httpPath', label: 'HTTP Path', type: 'text', placeholder: '/sql/1.0/warehouses/xxx', required: true },
      { id: 'token', label: 'Personal Access Token', type: 'password', required: true },
      { id: 'catalog', label: 'Catalog', type: 'text', required: false, defaultValue: 'hive_metastore' },
      { id: 'schema', label: 'Schema', type: 'text', required: false, defaultValue: 'default' },
    ],
    defaultPort: 443,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'google-cloud-sql',
    name: 'Google Cloud SQL',
    category: 'cloud-warehouse',
    icon: 'database',
    description: 'Fully managed relational database service on Google Cloud.',
    authMethods: ['username-password', 'service-account'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '5432', required: true, defaultValue: 5432 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'ssl', label: 'Require SSL', type: 'checkbox', required: false, defaultValue: true },
    ],
    defaultPort: 5432,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'azure-data-lake-gen2',
    name: 'Microsoft Azure Data Lake Gen 2',
    category: 'cloud-warehouse',
    icon: 'cloud',
    description: 'Scalable data lake storage with hierarchical namespace on Azure.',
    authMethods: ['service-account', 'oauth2'],
    fields: [
      { id: 'accountName', label: 'Storage Account Name', type: 'text', required: true },
      { id: 'container', label: 'Container', type: 'text', required: true },
      { id: 'accessKey', label: 'Access Key', type: 'password', required: true },
      { id: 'path', label: 'Path', type: 'text', required: false, placeholder: '/' },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'azure-synapse',
    name: 'Microsoft Azure Synapse',
    category: 'cloud-warehouse',
    icon: 'database',
    description: 'Limitless analytics service combining data warehousing and big data.',
    authMethods: ['username-password', 'service-account'],
    fields: [
      { id: 'host', label: 'Server', type: 'text', placeholder: 'workspace.sql.azuresynapse.net', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '1433', required: true, defaultValue: 1433 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 1433,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    category: 'cloud-warehouse',
    icon: 'snowflake',
    description: 'Cloud-native data platform with near-unlimited scalability.',
    authMethods: ['username-password', 'oauth2', 'api-key'],
    fields: [
      { id: 'account', label: 'Account Identifier', type: 'text', placeholder: 'org-account', required: true },
      { id: 'warehouse', label: 'Warehouse', type: 'text', required: true },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'schema', label: 'Schema', type: 'text', required: false, defaultValue: 'PUBLIC' },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'role', label: 'Role', type: 'text', required: false },
    ],
    defaultPort: 443,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'google-bigquery',
    name: 'Google BigQuery',
    category: 'cloud-warehouse',
    icon: 'database',
    description: 'Serverless, highly scalable multi-cloud data warehouse by Google.',
    authMethods: ['service-account', 'oauth2'],
    fields: [
      { id: 'projectId', label: 'Project ID', type: 'text', required: true },
      { id: 'dataset', label: 'Dataset', type: 'text', required: false },
      { id: 'serviceAccountKey', label: 'Service Account Key (JSON)', type: 'textarea', required: true },
      { id: 'location', label: 'Location', type: 'text', required: false, defaultValue: 'US' },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'qubole-presto',
    name: 'Qubole Presto',
    category: 'cloud-warehouse',
    icon: 'server',
    description: 'Managed Presto service for interactive analytics on cloud data.',
    authMethods: ['api-key'],
    fields: [
      { id: 'endpoint', label: 'API Endpoint', type: 'text', required: true },
      { id: 'apiToken', label: 'API Token', type: 'password', required: true },
      { id: 'cluster', label: 'Cluster Label', type: 'text', required: true },
      { id: 'catalog', label: 'Catalog', type: 'text', required: false, defaultValue: 'hive' },
      { id: 'schema', label: 'Schema', type: 'text', required: false, defaultValue: 'default' },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
];
