import { ConnectorDefinition } from '../types';

export const connectivityConnectors: ConnectorDefinition[] = [
  {
    id: 'jdbc',
    name: 'JDBC',
    category: 'connectivity',
    icon: 'plug',
    description: 'Connect to any database using a JDBC connection string.',
    authMethods: ['username-password', 'none'],
    fields: [
      { id: 'connectionUrl', label: 'JDBC URL', type: 'text', placeholder: 'jdbc:driver://host:port/database', required: true },
      { id: 'driverClass', label: 'Driver Class', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: false },
      { id: 'password', label: 'Password', type: 'password', required: false },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'odbc',
    name: 'ODBC',
    category: 'connectivity',
    icon: 'plug',
    description: 'Connect to any database using an ODBC data source name.',
    authMethods: ['username-password', 'none'],
    fields: [
      { id: 'dsn', label: 'Data Source Name (DSN)', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: false },
      { id: 'password', label: 'Password', type: 'password', required: false },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'apache-drill',
    name: 'Apache Drill',
    category: 'connectivity',
    icon: 'server',
    description: 'Schema-free SQL query engine for big data exploration.',
    authMethods: ['username-password', 'none'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '8047', required: true, defaultValue: 8047 },
      { id: 'schema', label: 'Schema', type: 'text', required: false },
      { id: 'username', label: 'Username', type: 'text', required: false },
      { id: 'password', label: 'Password', type: 'password', required: false },
    ],
    defaultPort: 8047,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'cloudera-hadoop',
    name: 'Cloudera Hadoop',
    category: 'connectivity',
    icon: 'server',
    description: 'Connect to Cloudera Hadoop clusters for big data analytics.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '10000', required: true, defaultValue: 10000 },
      { id: 'database', label: 'Database', type: 'text', required: false, defaultValue: 'default' },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: false },
      { id: 'transportMode', label: 'Transport Mode', type: 'select', required: true, defaultValue: 'binary', options: [{ label: 'Binary', value: 'binary' }, { label: 'HTTP', value: 'http' }] },
    ],
    defaultPort: 10000,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'cloudera-impala',
    name: 'Cloudera Impala',
    category: 'connectivity',
    icon: 'server',
    description: 'Massively parallel processing SQL engine on Hadoop.',
    authMethods: ['username-password', 'none'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '21050', required: true, defaultValue: 21050 },
      { id: 'database', label: 'Database', type: 'text', required: false, defaultValue: 'default' },
      { id: 'username', label: 'Username', type: 'text', required: false },
      { id: 'password', label: 'Password', type: 'password', required: false },
      { id: 'authMechanism', label: 'Auth Mechanism', type: 'select', required: true, defaultValue: 'NOSASL', options: [{ label: 'No SASL', value: 'NOSASL' }, { label: 'LDAP', value: 'LDAP' }, { label: 'Kerberos', value: 'GSSAPI' }] },
    ],
    defaultPort: 21050,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'hortonworks-hadoop-hive',
    name: 'Hortonworks Hadoop Hive',
    category: 'connectivity',
    icon: 'server',
    description: 'Connect to Hortonworks Data Platform Hive for SQL on Hadoop.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '10000', required: true, defaultValue: 10000 },
      { id: 'database', label: 'Database', type: 'text', required: false, defaultValue: 'default' },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: false },
      { id: 'transportMode', label: 'Transport Mode', type: 'select', required: true, defaultValue: 'binary', options: [{ label: 'Binary', value: 'binary' }, { label: 'HTTP', value: 'http' }] },
    ],
    defaultPort: 10000,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'mapr-hadoop-hive',
    name: 'MapR Hadoop Hive',
    category: 'connectivity',
    icon: 'server',
    description: 'Connect to MapR Data Platform Hive for SQL on Hadoop.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '10000', required: true, defaultValue: 10000 },
      { id: 'database', label: 'Database', type: 'text', required: false, defaultValue: 'default' },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: false },
    ],
    defaultPort: 10000,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'ibm-biginsights',
    name: 'IBM BigInsights',
    category: 'connectivity',
    icon: 'server',
    description: 'IBM analytics platform for Hadoop-based big data.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '10000', required: true, defaultValue: 10000 },
      { id: 'database', label: 'Database', type: 'text', required: false, defaultValue: 'default' },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 10000,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'sftp',
    name: 'SFTP',
    category: 'connectivity',
    icon: 'upload',
    description: 'Secure file transfer protocol for accessing remote files.',
    authMethods: ['username-password', 'api-key'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '22', required: true, defaultValue: 22 },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: false },
      { id: 'privateKey', label: 'Private Key', type: 'textarea', required: false },
      { id: 'remotePath', label: 'Remote Path', type: 'text', required: false, placeholder: '/' },
    ],
    defaultPort: 22,
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'ftps',
    name: 'FTPS',
    category: 'connectivity',
    icon: 'upload',
    description: 'FTP over TLS/SSL for secure file transfers.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '990', required: true, defaultValue: 990 },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'remotePath', label: 'Remote Path', type: 'text', required: false, placeholder: '/' },
      { id: 'implicit', label: 'Implicit TLS', type: 'checkbox', required: false, defaultValue: true },
    ],
    defaultPort: 990,
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'odata',
    name: 'OData',
    category: 'connectivity',
    icon: 'globe',
    description: 'Open Data Protocol for querying RESTful data services.',
    authMethods: ['username-password', 'oauth2', 'api-key', 'none'],
    fields: [
      { id: 'serviceUrl', label: 'Service URL', type: 'text', placeholder: 'https://services.odata.org/V4/Northwind/', required: true },
      { id: 'username', label: 'Username', type: 'text', required: false },
      { id: 'password', label: 'Password', type: 'password', required: false },
      { id: 'apiKey', label: 'API Key', type: 'password', required: false },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: false,
  },
  {
    id: 'graphql',
    name: 'GraphQL',
    category: 'connectivity',
    icon: 'globe',
    description: 'Query language for APIs with flexible data fetching.',
    authMethods: ['none', 'api-key', 'oauth2'],
    fields: [
      { id: 'endpoint', label: 'GraphQL Endpoint', type: 'text', placeholder: 'https://api.example.com/graphql', required: true },
      { id: 'authType', label: 'Authentication', type: 'select', required: true, defaultValue: 'none', options: [{ label: 'None', value: 'none' }, { label: 'Bearer Token', value: 'bearer' }, { label: 'API Key', value: 'api-key' }] },
      { id: 'token', label: 'Token', type: 'password', required: false, dependsOn: { field: 'authType', value: 'bearer' } },
      { id: 'apiKey', label: 'API Key', type: 'password', required: false, dependsOn: { field: 'authType', value: 'api-key' } },
      { id: 'headers', label: 'Custom Headers (JSON)', type: 'textarea', required: false, placeholder: '{"Content-Type": "application/json"}' },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: false,
  },
];
