import { ConnectorDefinition } from '../types';

export const databases: ConnectorDefinition[] = [
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'database',
    icon: 'database',
    description: 'Powerful open-source relational database with advanced features.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '5432', required: true, defaultValue: 5432 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'ssl', label: 'Require SSL', type: 'checkbox', required: false, defaultValue: false },
    ],
    defaultPort: 5432,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'mysql',
    name: 'MySQL',
    category: 'database',
    icon: 'database',
    description: 'Popular open-source relational database management system.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '3306', required: true, defaultValue: 3306 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'ssl', label: 'Require SSL', type: 'checkbox', required: false, defaultValue: false },
    ],
    defaultPort: 3306,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'mssql',
    name: 'Microsoft SQL Server',
    category: 'database',
    icon: 'database',
    description: 'Enterprise relational database from Microsoft.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Server', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '1433', required: true, defaultValue: 1433 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'encrypt', label: 'Encrypt Connection', type: 'checkbox', required: false, defaultValue: true },
      { id: 'trustServerCertificate', label: 'Trust Server Certificate', type: 'checkbox', required: false, defaultValue: false },
    ],
    defaultPort: 1433,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'oracle',
    name: 'Oracle',
    category: 'database',
    icon: 'database',
    description: 'Enterprise-grade relational database management system.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '1521', required: true, defaultValue: 1521 },
      { id: 'serviceName', label: 'Service Name', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 1521,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'mariadb',
    name: 'MariaDB',
    category: 'database',
    icon: 'database',
    description: 'Community-developed fork of MySQL with enhanced features.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '3306', required: true, defaultValue: 3306 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'ssl', label: 'Require SSL', type: 'checkbox', required: false, defaultValue: false },
    ],
    defaultPort: 3306,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'ibm-db2',
    name: 'IBM DB2',
    category: 'database',
    icon: 'database',
    description: 'Enterprise relational database from IBM for mission-critical workloads.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '50000', required: true, defaultValue: 50000 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 50000,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'ibm-netezza',
    name: 'IBM Netezza',
    category: 'database',
    icon: 'database',
    description: 'High-performance data warehouse appliance from IBM.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '5480', required: true, defaultValue: 5480 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 5480,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'database',
    icon: 'database',
    description: 'Document-oriented NoSQL database for modern applications.',
    authMethods: ['username-password'],
    fields: [
      { id: 'connectionString', label: 'Connection String', type: 'text', placeholder: 'mongodb://host:27017/db', required: true },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: false },
      { id: 'password', label: 'Password', type: 'password', required: false },
      { id: 'authSource', label: 'Auth Source', type: 'text', required: false, defaultValue: 'admin' },
    ],
    defaultPort: 27017,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    category: 'database',
    icon: 'database',
    description: 'Column-oriented OLAP database for real-time analytics.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '8123', required: true, defaultValue: 8123 },
      { id: 'database', label: 'Database', type: 'text', required: true, defaultValue: 'default' },
      { id: 'username', label: 'Username', type: 'text', required: true, defaultValue: 'default' },
      { id: 'password', label: 'Password', type: 'password', required: false },
    ],
    defaultPort: 8123,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'sap-hana',
    name: 'SAP HANA',
    category: 'database',
    icon: 'database',
    description: 'In-memory relational database from SAP for real-time analytics.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '30015', required: true, defaultValue: 30015 },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'schema', label: 'Schema', type: 'text', required: false },
    ],
    defaultPort: 30015,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'sap-sybase-iq',
    name: 'SAP Sybase IQ',
    category: 'database',
    icon: 'database',
    description: 'Column-based analytics server from SAP for data warehousing.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '2638', required: true, defaultValue: 2638 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 2638,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'sap-sybase-ase',
    name: 'SAP Sybase ASE',
    category: 'database',
    icon: 'database',
    description: 'High-performance OLTP relational database from SAP.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '5000', required: true, defaultValue: 5000 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 5000,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'teradata',
    name: 'Teradata',
    category: 'database',
    icon: 'database',
    description: 'Enterprise data warehouse platform for large-scale analytics.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '1025', required: true, defaultValue: 1025 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 1025,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'hp-vertica',
    name: 'HP Vertica',
    category: 'database',
    icon: 'database',
    description: 'Column-oriented analytics database for large-scale data.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '5433', required: true, defaultValue: 5433 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 5433,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'exasol',
    name: 'Exasol',
    category: 'database',
    icon: 'database',
    description: 'High-performance in-memory analytics database.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '8563', required: true, defaultValue: 8563 },
      { id: 'schema', label: 'Schema', type: 'text', required: false },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 8563,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'pivotal-greenplum',
    name: 'Pivotal Greenplum',
    category: 'database',
    icon: 'database',
    description: 'Massively parallel processing data warehouse based on PostgreSQL.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '5432', required: true, defaultValue: 5432 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 5432,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'monetdb',
    name: 'MonetDB',
    category: 'database',
    icon: 'database',
    description: 'Column-store database for high-performance analytics.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '50000', required: true, defaultValue: 50000 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 50000,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'singlestore',
    name: 'SingleStore',
    category: 'database',
    icon: 'database',
    description: 'Distributed SQL database for real-time analytics and transactions.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '3306', required: true, defaultValue: 3306 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 3306,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'microsoft-access',
    name: 'Microsoft Access',
    category: 'database',
    icon: 'database',
    description: 'Desktop relational database from Microsoft Office suite.',
    authMethods: ['none', 'username-password'],
    fields: [
      { id: 'filePath', label: 'Database File Path', type: 'text', placeholder: '/path/to/database.accdb', required: true },
      { id: 'password', label: 'Password', type: 'password', required: false },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'kognitio',
    name: 'Kognitio',
    category: 'database',
    icon: 'database',
    description: 'In-memory analytical platform for high-performance queries.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '6550', required: true, defaultValue: 6550 },
      { id: 'schema', label: 'Schema', type: 'text', required: false },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 6550,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'kyvos',
    name: 'Kyvos',
    category: 'database',
    icon: 'database',
    description: 'BI acceleration platform with smart OLAP cubes on big data.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '443', required: true, defaultValue: 443 },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 443,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'marklogic',
    name: 'MarkLogic',
    category: 'database',
    icon: 'database',
    description: 'Multi-model NoSQL database for complex data integration.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '8000', required: true, defaultValue: 8000 },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
    ],
    defaultPort: 8000,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'presto',
    name: 'Presto',
    category: 'database',
    icon: 'server',
    description: 'Distributed SQL query engine for big data analytics.',
    authMethods: ['username-password', 'none'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '8080', required: true, defaultValue: 8080 },
      { id: 'catalog', label: 'Catalog', type: 'text', required: true },
      { id: 'schema', label: 'Schema', type: 'text', required: false, defaultValue: 'default' },
      { id: 'username', label: 'Username', type: 'text', required: false },
    ],
    defaultPort: 8080,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'sparksql',
    name: 'SparkSQL',
    category: 'database',
    icon: 'zap',
    description: 'SQL interface for Apache Spark distributed data processing.',
    authMethods: ['username-password', 'none'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '10000', required: true, defaultValue: 10000 },
      { id: 'database', label: 'Database', type: 'text', required: false, defaultValue: 'default' },
      { id: 'username', label: 'Username', type: 'text', required: false },
      { id: 'password', label: 'Password', type: 'password', required: false },
    ],
    defaultPort: 10000,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'cockroachdb',
    name: 'CockroachDB',
    category: 'database',
    icon: 'database',
    description: 'Distributed SQL database for global cloud-native applications.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '26257', required: true, defaultValue: 26257 },
      { id: 'database', label: 'Database', type: 'text', required: true, defaultValue: 'defaultdb' },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'ssl', label: 'Require SSL', type: 'checkbox', required: false, defaultValue: true },
    ],
    defaultPort: 26257,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'cassandra',
    name: 'Cassandra',
    category: 'database',
    icon: 'database',
    description: 'Distributed NoSQL database for high-availability workloads.',
    authMethods: ['username-password', 'none'],
    fields: [
      { id: 'host', label: 'Contact Points', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '9042', required: true, defaultValue: 9042 },
      { id: 'keyspace', label: 'Keyspace', type: 'text', required: true },
      { id: 'username', label: 'Username', type: 'text', required: false },
      { id: 'password', label: 'Password', type: 'password', required: false },
      { id: 'datacenter', label: 'Local Datacenter', type: 'text', required: false },
    ],
    defaultPort: 9042,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'database',
    icon: 'database',
    description: 'In-memory data store used as database, cache, and message broker.',
    authMethods: ['username-password', 'none'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '6379', required: true, defaultValue: 6379 },
      { id: 'password', label: 'Password', type: 'password', required: false },
      { id: 'database', label: 'Database Index', type: 'number', required: false, defaultValue: 0 },
      { id: 'ssl', label: 'Use TLS', type: 'checkbox', required: false, defaultValue: false },
    ],
    defaultPort: 6379,
    supportsSchemaDiscovery: false,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'neo4j',
    name: 'Neo4j',
    category: 'database',
    icon: 'share-2',
    description: 'Graph database for connected data and relationship analytics.',
    authMethods: ['username-password'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '7687', required: true, defaultValue: 7687 },
      { id: 'database', label: 'Database', type: 'text', required: false, defaultValue: 'neo4j' },
      { id: 'username', label: 'Username', type: 'text', required: true },
      { id: 'password', label: 'Password', type: 'password', required: true },
      { id: 'encrypted', label: 'Use Encryption', type: 'checkbox', required: false, defaultValue: false },
    ],
    defaultPort: 7687,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    category: 'database',
    icon: 'search',
    description: 'Distributed search and analytics engine for all types of data.',
    authMethods: ['username-password', 'api-key', 'none'],
    fields: [
      { id: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { id: 'port', label: 'Port', type: 'number', placeholder: '9200', required: true, defaultValue: 9200 },
      { id: 'username', label: 'Username', type: 'text', required: false },
      { id: 'password', label: 'Password', type: 'password', required: false },
      { id: 'ssl', label: 'Use SSL', type: 'checkbox', required: false, defaultValue: false },
      { id: 'index', label: 'Index Pattern', type: 'text', required: false, placeholder: '*' },
    ],
    defaultPort: 9200,
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
  {
    id: 'dynamodb',
    name: 'DynamoDB',
    category: 'database',
    icon: 'database',
    description: 'Fully managed NoSQL key-value database by Amazon Web Services.',
    authMethods: ['api-key', 'iam-role'],
    fields: [
      { id: 'region', label: 'AWS Region', type: 'text', placeholder: 'us-east-1', required: true },
      { id: 'accessKeyId', label: 'Access Key ID', type: 'password', required: true },
      { id: 'secretAccessKey', label: 'Secret Access Key', type: 'password', required: true },
      { id: 'tableName', label: 'Table Name', type: 'text', required: false },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: false,
    proxyRequired: true,
  },
  {
    id: 'cosmos-db',
    name: 'Cosmos DB',
    category: 'database',
    icon: 'database',
    description: 'Globally distributed multi-model database by Microsoft Azure.',
    authMethods: ['api-key'],
    fields: [
      { id: 'endpoint', label: 'Account Endpoint', type: 'text', placeholder: 'https://account.documents.azure.com:443/', required: true },
      { id: 'accountKey', label: 'Account Key', type: 'password', required: true },
      { id: 'database', label: 'Database', type: 'text', required: true },
      { id: 'container', label: 'Container', type: 'text', required: false },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: true,
    proxyRequired: true,
  },
];
