import { ConnectorDefinition } from '../types';

export const fileConnectors: ConnectorDefinition[] = [
  {
    id: 'microsoft-excel',
    name: 'Microsoft Excel',
    category: 'file',
    icon: 'file-spreadsheet',
    description: 'Import data from Excel workbooks (.xlsx, .xls).',
    authMethods: ['none'],
    fields: [
      { id: 'file', label: 'Excel File', type: 'file', required: true },
      { id: 'sheetName', label: 'Sheet Name', type: 'text', required: false, placeholder: 'First sheet by default' },
      { id: 'headerRow', label: 'Header Row', type: 'number', required: false, defaultValue: 1, validation: { min: 1 } },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'pdf',
    name: 'PDF',
    category: 'file',
    icon: 'file-text',
    description: 'Extract tabular data from PDF documents.',
    authMethods: ['none'],
    fields: [
      { id: 'file', label: 'PDF File', type: 'file', required: true },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'text-file',
    name: 'Text files',
    category: 'file',
    icon: 'file-text',
    description: 'Import delimited text files (.csv, .tsv, .txt).',
    authMethods: ['none'],
    fields: [
      { id: 'file', label: 'Text File', type: 'file', required: true },
      { id: 'delimiter', label: 'Delimiter', type: 'select', required: true, defaultValue: ',', options: [{ label: 'Comma (,)', value: ',' }, { label: 'Tab (\\t)', value: '\t' }, { label: 'Semicolon (;)', value: ';' }, { label: 'Pipe (|)', value: '|' }] },
      { id: 'quoteChar', label: 'Quote Character', type: 'select', required: false, defaultValue: '"', options: [{ label: 'Double Quote (")', value: '"' }, { label: "Single Quote (')", value: "'" }, { label: 'None', value: '' }] },
      { id: 'encoding', label: 'Encoding', type: 'select', required: false, defaultValue: 'utf-8', options: [{ label: 'UTF-8', value: 'utf-8' }, { label: 'Latin-1', value: 'latin1' }, { label: 'Windows-1252', value: 'windows-1252' }] },
      { id: 'headerRow', label: 'Header Row', type: 'number', required: false, defaultValue: 1, validation: { min: 1 } },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'statistical-file',
    name: 'Statistical files',
    category: 'file',
    icon: 'bar-chart',
    description: 'Import statistical data files (.sav, .dta, .sas7bdat).',
    authMethods: ['none'],
    fields: [
      { id: 'file', label: 'Statistical File', type: 'file', required: true },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'csv',
    name: 'CSV',
    category: 'file',
    icon: 'file-text',
    description: 'Import comma-separated values files.',
    authMethods: ['none'],
    fields: [
      { id: 'file', label: 'CSV File', type: 'file', required: true },
      { id: 'delimiter', label: 'Delimiter', type: 'select', required: true, defaultValue: ',', options: [{ label: 'Comma (,)', value: ',' }, { label: 'Semicolon (;)', value: ';' }, { label: 'Tab (\\t)', value: '\t' }, { label: 'Pipe (|)', value: '|' }] },
      { id: 'encoding', label: 'Encoding', type: 'select', required: false, defaultValue: 'utf-8', options: [{ label: 'UTF-8', value: 'utf-8' }, { label: 'Latin-1', value: 'latin1' }, { label: 'Windows-1252', value: 'windows-1252' }] },
      { id: 'headerRow', label: 'Header Row', type: 'number', required: false, defaultValue: 1, validation: { min: 1 } },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'json',
    name: 'JSON',
    category: 'file',
    icon: 'file-code',
    description: 'Import data from JSON files with array or object structures.',
    authMethods: ['none'],
    fields: [
      { id: 'file', label: 'JSON File', type: 'file', required: true },
      { id: 'dataPath', label: 'Data Path', type: 'text', required: false, placeholder: 'data.results' },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'xml',
    name: 'XML',
    category: 'file',
    icon: 'file-code',
    description: 'Import structured data from XML files.',
    authMethods: ['none'],
    fields: [
      { id: 'file', label: 'XML File', type: 'file', required: true },
      { id: 'rowTag', label: 'Row Tag', type: 'text', required: false, placeholder: 'record' },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'parquet',
    name: 'Parquet',
    category: 'file',
    icon: 'file',
    description: 'Import columnar data from Apache Parquet files.',
    authMethods: ['none'],
    fields: [
      { id: 'file', label: 'Parquet File', type: 'file', required: true },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'spss',
    name: 'SPSS',
    category: 'file',
    icon: 'bar-chart',
    description: 'Import data from IBM SPSS Statistics files (.sav).',
    authMethods: ['none'],
    fields: [
      { id: 'file', label: 'SPSS File (.sav)', type: 'file', required: true },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'stata',
    name: 'Stata',
    category: 'file',
    icon: 'bar-chart',
    description: 'Import data from Stata statistical files (.dta).',
    authMethods: ['none'],
    fields: [
      { id: 'file', label: 'Stata File (.dta)', type: 'file', required: true },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'sas',
    name: 'SAS',
    category: 'file',
    icon: 'bar-chart',
    description: 'Import data from SAS data files (.sas7bdat).',
    authMethods: ['none'],
    fields: [
      { id: 'file', label: 'SAS File (.sas7bdat)', type: 'file', required: true },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    category: 'file',
    icon: 'file-spreadsheet',
    description: 'Import data from Google Sheets spreadsheets.',
    authMethods: ['oauth2'],
    fields: [
      { id: 'oauth', label: 'Sign in with Google', type: 'oauth-button', required: true },
      { id: 'spreadsheetUrl', label: 'Spreadsheet URL', type: 'text', placeholder: 'https://docs.google.com/spreadsheets/d/...', required: true },
      { id: 'sheetName', label: 'Sheet Name', type: 'text', required: false, placeholder: 'First sheet by default' },
    ],
    supportsSchemaDiscovery: false,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'file',
    icon: 'table',
    description: 'Import data from Airtable bases and tables.',
    authMethods: ['api-key', 'oauth2'],
    fields: [
      { id: 'apiKey', label: 'API Key', type: 'password', required: true },
      { id: 'baseId', label: 'Base ID', type: 'text', required: true },
      { id: 'tableName', label: 'Table Name', type: 'text', required: true },
    ],
    supportsSchemaDiscovery: true,
    supportsCustomQuery: false,
    proxyRequired: false,
  },
];
